#!/usr/bin/env python

import re
import sys

errfile = "<sinc>"

def read(sexpr):
    grammar = r"(\()|(\))|([^()\s]+)|(\s+)"

    def sequenceBuilder(match):
        leftbracket, rightbracket, atom, whitespace = match.groups()
        if(leftbracket): return '['
        elif(rightbracket): return ']'
        elif(atom): return '"' + atom + '"'
        elif(whitespace): return ','
    return eval(re.sub(grammar, sequenceBuilder, sexpr), None, None)

def set(rest):
    if(len(rest) == 2): # a variable
        globalScope.append((comp(rest[0]), comp(rest[1])))
    else: # a function
        globalScope.append((comp(rest[0]), "lambda " + comp(rest[1]).strip("[]") +": " + comp(rest[2])))
    return "None" 

specialForms = {
    "set": set,
    "first": lambda rest: "(" + comp(rest[0]) + ")[0]",
    "rest": lambda rest: "(" + comp(rest[0]) + ")[1:]",
    "cons": lambda rest: "[" + comp(rest[0])+"] + " + comp(rest[1]),
    "quote": lambda rest: "[" + ", ".join(map(lambda x: comp(x), rest)) + "]",
    "eq": lambda rest: "("+comp(rest[0])+" == "+comp(rest[1])+")",
    "cond": lambda rest: "("+comp(rest[1])+" if "+comp(rest[0])+" else "+comp(rest[2])+")",
    "+": lambda rest: comp(rest[0])+" + "+comp(rest[1]),
    "-": lambda rest: comp(rest[0])+" - "+comp(rest[1]),
    "*": lambda rest: "("+comp(rest[0])+") * ("+comp(rest[1])+")",
    "/": lambda rest: "("+comp(rest[0])+") / ("+comp(rest[1])+")"
}

globalScope = []
def comp(tree):
    if(type(tree) == list):
        if(tree[0] in specialForms):
            return specialForms.get(tree[0])(tree[1:])
        else:
            args = map(lambda x: comp(x), tree[1:])
            return tree[0] + "(" + ",".join(args) + ")"
    else:
        return tree

def transcribe(sexpr):
    tree = read(sexpr)
    if(type(tree) == tuple):
        transcripts = []
        for node in tree:
            transcripts.append(comp(node))
        transcript = "\n".join(transcripts)
    else:
        transcript = comp(tree)

    initCode = []
    for expr in globalScope:
        initCode.append(str(expr[0]) + " = " + str(expr[1]) + "\n")
    return "".join(initCode) + transcript

def sinc(sexpr):
    transcript = transcribe(sexpr)
    print transcript

def repl():
    while(True):
        print "sinC> ",
        sys.stdout.flush()
        line = sys.stdin.readline().lstrip(">").strip() 
        try:
            sinc(line)
        except:
            print "???"

if __name__ == "__main__":
    if(len(sys.argv) == 2):
        f = open(sys.argv[1])
        sinc(f.read())
        f.close()

    else:
        print "This is sinC-alpha. Interactice LISP to Python compiler."
        print
        repl()

"""
e1 = "(+ 1 2)"
e2 = "(set var content)"
e3 = "(set inc (quote x) (+ x (+ 0.5 0.5)))"
e4 = "(inc 4)"

factorial = "(set factorial (quote x) (cond (eq x 1) 1 (* (factorial (- x 1)) x)))"
fibonacci = "(set fib (quote x) (cond (eq x 0) 1 (+ (fib (- x 1)) x)))"
"""
